### ISSUE TITLE
I had trouble building the benchmark.

### ISSUE THREAD

**Issue by cqujk** [cwida/ALP#20]
![image](https://github.com/user-attachments/assets/90c3dee1-193b-476f-b200-912acb51ca3c)
![image](https://github.com/user-attachments/assets/c9794524-a306-438b-8ba4-92f7c90b7851)
What does ALP_DATASET_DIR_PATH mean and what does it represent?

**Comment by azimafroozeh** [comment]
Thank you for your question!

`ALP_DATASET_DIR_PATH` refers to the directory path where the dataset we used for benchmarking ALP is located. This path is essential when setting up the environment for running benchmarks.

For more details on the dataset, including instructions on how to download and use it, please refer to the [benchmarking documentation](https://github.com/cwida/ALP/blob/main/BENCHMARKING.md).

Regarding your second screenshot, I have renamed the targets. You can check the changes in #21  and the issue should now be resolved.

**Comment by cqujk** [comment]
Thank you!Do the projects downloaded from GitHub come without test data? I tried using this command `export ALP_DATASET_DIR_PATH=/home/jk/learn/project/ALP/data/double/test_0.csv` to specify ALP, although it may not be the key to the problem I am encountering. What is placed in the data directory under that? Should the data be downloaded and placed there, and then specified by the same command?

**Comment by azimafroozeh** [comment]
Some parts of the dataset are already included in the GitHub repository. However, due to size constraints, the remaining data is hosted separately on Google Drive. You can download it from [this link](https://drive.google.com/drive/folders/167faTwZJjqJMKM9Yc6E7KF5LUbsitxJS).

After downloading and unzipping the file, set the `ALP_DATASET_DIR_PATH` to the unzipped directory using your export command.

**Comment by cqujk** [comment]
Thank you!
