### ISSUE TITLE
Cannot use my own datasets with ALP Benchmark

### ISSUE THREAD

**Issue by aabduvakhobov** [cwida/ALP#8]
Hi, 

I am trying to use the existing benchmark in ALP repository with my own datasets. I followed the documentation to plug in my datasets and all the methods are working, but ALP. The new datasets were preprocessed using the same method as in the [datasets_transformer.ipynb](https://github.com/cwida/ALP/blob/main/data/datasets_transformer.ipynb). Also I made sure that my data doesn't have null, nan, inf, -inf values. The size of the data is also larger than some existing data in the benchmark.

Thank you!

**Comment by azimafroozeh** [comment]
No worries at all! That would be ideal if you could replicate the issue with an open dataset. I'll be happy to look into it further once you have the dataset ready. Looking forward to hearing back from you!

**Comment by aabduvakhobov** [comment]
Thanks! You can find the sample csv dataset. I converted it to the text format to be able to attach it here. In the experiments, I am feeding it as binary file. So far, I am running the benchmark for compression ratio, thus I am not specifying other parameters like exponent, factor and exceptions amount the  [data/include/double_columns.hpp](https://github.com/cwida/ALP/blob/main/data/include/double_columns.hpp) file. Perhaps I have to compute them to be able to do it.
[active_power.csv](https://github.com/user-attachments/files/16964802/active_power.csv)

**Comment by azimafroozeh** [comment]
Thank you for providing the dataset. I have submitted a PR (#9) that includes your dataset in our testing framework. 

So, there is no issue with ALP. ALP consists of two schemes, `ALP_RD` and `ALP`, which are selected adaptively based on data. My guess is that you might have used tests designed for internal ALP, whereas your dataset is suited for ALP_RD. You may want to check the tests at https://github.com/cwida/ALP/blob/5f1ff16e601f5ff11bef65036fbc0232bf38524f/benchmarks/bench_compression_ratio/alp.cpp#L259.

**Comment by azimafroozeh** [comment]
Thanks for your questions!

1. `ALP` works best for doubles representing decimal-like numbers rather than real doubles, which use every bit for precision. For example, `10.3` is a decimal-like double, while `10.334324352532` is a real double. ALP compresses these "decimal" doubles by converting them into decimals. On the other hand, `ALP_RD` is designed for real doubles, where precision is extremely high, and there's little similarity in the right bits. Your dataset consists of real doubles, making `ALP_RD` the better choice. The fallback occurs because `ALP` tries to encode a sample of the data first and switches to `ALP_RD` as no compression opportunities are found. You can find more detailed explanations in our paper [here](https://dl.acm.org/doi/pdf/10.1145/3626717).

2) The practicality of `ALP` for 32-bit floats depends on the dataset. In our experiments with real datasets, we found that most floats behave like real floats (similar to real doubles), where `ALP_RD` is more effective. However, if your floats resemble decimal-like values, `ALP` could indeed work well. We are considering adding support for `ALP` for floats as well.

3) When benchmarking [de]compression speeds, there’s no need to validate exceptions or bit-widths, as long as the decoded values match the original values after encoding and decoding. Our internal checks are mainly to ensure that `ALP` behaves as expected rather than validating the final results.

4) Thank you for sharing the EDBT 2024 paper and datasets. We will include them in our testing.

Feel free to reach out if you have more questions!

**Comment by peterboncz** [comment]
Note that if your doubles (or floats) have deep precision but you only care about limited precision, one trick is to cast the doubles to integer and then back.For instance, if you consider three digits of precision enough and your floats are between 0.0 and 1.0; you could cast to integer and then back to double, eg 0.001 * (int) (value*1000). The resulting doubles will compress to 10bits per value (6.4x) in ALP. Op 12 sep. 2024 om 16:36 heeft Abduvoris Abduvakhobov ***@***.***> het volgende geschreven:﻿
Thanks a lot for your detailed response and hope to see ALP for floats soon.
Wish you best of luck in the future!
Cheers.

**Comment by aabduvakhobov** [comment]
Hi, thanks for the idea! We also had the idea of trimming the unnecessary decimals for lossy compression and compress using the latest lightweight encoding algorithms. ALP seems to fit this scenario very well.

**Comment by azimafroozeh** [comment]
Hi, we have added all the primitives for the float implementation of ALP. Please check [here](https://github.com/cwida/ALP/blob/392bec6b4a90b1e626fc64639dedbf9e7133567b/test/test_alp_sample.cpp#L211). Moreover, you can use the FastLanes double encoder to encode the double data type with ALP. FastLanes will handle the low-level details of ALP and provide a better API. Please check an example of the FastLanes double encoder [here](https://github.com/cwida/FastLanes/blob/4d7fa1eee62f33769284818917dc4e9ccd11e4b9/example/cpp_example.cpp#L10).

**Comment by aabduvakhobov** [comment]
Hi, this is very helpful indeed. I am closing the issue and many thanks for your help!
